### ISSUE TITLE
reindex is getting an elastic search error

### ISSUE THREAD

**Issue by tylerl0706** [promptworks/elastic_sync#4]
I accidentally deleted my index and so I attempted to use the reindex to re-create my index. I ran the reindex command and received:

```
> mix elastic_sync.reindex Nesgames.SyncRepo Nesgames.Game                                                                                  

01:53:17.242 [debug] QUERY OK source="games" db=5.8ms decode=6.7ms queue=42.6ms
SELECT g0."id", g0."title", g0."eurelease", g0."narelease", g0."publisher", g0."inserted_at", g0."updated_at" FROM "games" AS g0 []
** (MatchError) no match of right hand side value: :error
    lib/elastic_sync/sync_repo.ex:93: ElasticSync.SyncRepo.reindex/2
    lib/mix/tasks/elastic_sync/reindex.ex:13: Mix.Tasks.ElasticSync.Reindex.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

It seems to be failing here:

```
# Create a new index with the name of the alias
    {:ok, _, _} = search.create_index(alias_name)
```

I'm running Elastic Search in a Docker container so the config in my Phoenix project required  changing for the non-default port.

Let me know how I can help!

**Comment by rzane** [comment]
First, I want to make it clear that this project is being actively developed, and the reason I haven't put it on hex.pm yet is because I'm not 100% confident in it yet.

This error happened because it failed to create a new index. You can simulate this by running `curl -XPUT http://localhost:9200/test-index`. The most likely causes for it failing to create an index are:

1. An index with that name already exists.
2. Elasticsearch isn't running, or isn't accessible at the endpoint you've configured.

You might want to consider trying master, because I made some reindexing improvements. I'll definitely work on better error messages for this sort of thing!

**Comment by tylerl0706** [comment]
Thanks for the quick response! I have to say that for something you're not
confident about yet, this whole project is really quite amazing.

I added elastic_sync to my project and 10 minutes later, it just worked!

So I'd like to say I really like this project and I hope that these words
encourage you to keep it up!

Now I must confess, I had the wrong port configuration. You were right.
When my laptop restarted, the port for Elasticsearch changed...

Thanks for the help! I'd be interested in getting involved with this
project! The fair warning is that I've very new to elixir so I wouldn't be
able to help too much in the beginning.

Looking forward to seeing where this project goes!

**Comment by rzane** [comment]
That's great to hear. Thanks!

If you're interested in contributing, here is some low-hanging fruit:

1. The mix task doesn't offer any useful output. I'd like to display some sort of progress indication, as well as provide some better error feedback.
2. I'm barely using Tirexs. I should be using it to handle all of the URL generation.
3. Index names need to be properly parameterized. For example, convert `foo bar` into `foo_bar`.
